//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsChatApi.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public long UserId { get; set; }
        public string Username { get; set; }
        public bool LoggedIn { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
    }
}
